#!/bin/csh

# 1) converts to AFNI, 2) performs outlier detection, 3) optional skull stripping, 4) conversion to taliarach coords
# 5) realigns functional data to static template coords
# can be used on Fear Acq, Fear Ext, MID 1 or MID 2, with appropriate options at start
# comment out Structural conversion after first run!

#scanner = trio / prisma / ge
set scanner = ge
foreach task (FearAcq)
#task = FearAcq, FearExt, MID1, MID2
#set task = MID2
#parts to run ALL (conversion, outlier detection, convert to taliarach & realign), SS = skull strip, DSB = despike/blur, mp = just midpoint
set run = ALL

#-------------------------------------------------------------------------------------#
#set scan path
if (${scanner} == "trio") then
set study_dir = /space/raid6/data/craske/POS_NEG_EMO_RDOC/01_SUBJECTS_UCLA_TRIO
else if (${scanner} == "prisma") then
set study_dir = /space/raid6/data/craske/POS_NEG_EMO_RDOC/02_SUBJECTS_UCLA_PRISMA 	
else if (${scanner} == "ge") then
set study_dir = /space/raid6/data/craske/POS_NEG_EMO_RDOC/03_SUBJECTS_UCSD
else
echo "error setting scanner"
endif
echo "\nscanner: ${scanner}"


foreach subj (0106201503) #(`cat AFNI_list`)
#TRIO
#9201 9202 9203 9204 9205 9206 9207 9208 9209 9211 
#9212 9213 9216 9217 9218 9219 9223 9224 9225 9226 
#9227 9228 9230 9231 9232 9233 9235 9236 9237 9238 
#9239 9241 9242 9243 9244 9245 9246 9247 9248 9251 
#9252 9254 9255 9257 9258 9259 9260 9261 9263 9264 
#9265 9266 9267 9268 9270 9271 9273 9274 9277 9279 
#9282 9283 9284 9285 9286 9287 9288 9289 9290

#PRISMA
#9292 9293 9294 9295 9296 9298 9300 9301 9302 9303 
#9304 9305 9306 9307 9308 9309 9310 9311 9312 9314 
#9315 9316 9317 9318 9319 9320 9321 9322 9323 9324 
#9325 9326 9327 9328

#GE
#0106201503 0113201601 0114201601 0123201501 0128201501 0128201502 0129201601 0204201502 0210201501 0211201502 0215201601 0218201601 0305201501 0308201601 0308201602 0308201604 0310201501 0310201502 0404201403 0406201601 0406201602 0407201601 0407201602 0413201601 0416201502 0419201601 0424201401 0425201502 0427201401 0427201601 0430201401 0503201401 0506201402 0512201501 0516201601 0517201501 0519201401 0519201501 0520201401 0520201501 0520201502 0520201601 0522201402 0524201602 0620201601 0714201401 0727201601 0804201503 0807201502 0808201603 0811201401 0811201402 0811201403 0812201402 0818201401 0818201403 0828201403 0829201401 0902201401 0904201405 0905201401 0906201401 0910201401 0911201501 0916201501 0930201401 1016201502 1022201401 1028201401 1105201502 1106201403 1109201401 1114201401 1118201402 1119201503 1120201401 1210201401 1210201402 1210201501 1215201401 1218201402 1218201403 1218201501 1219201402

#set task files%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if (${task} == "FearAcq") then
set task_dir = Fear_cond/Fear_acq
else if (${task} == "FearExt") then
set task_dir = Fear_cond/Fear_ext 
else if (${task} == "MID1") then
set task_dir = MID/Part1
else if (${task} == "MID2") then
set task_dir = MID/Part2
else
echo "error setting task files"
endif

echo "\ntask: ${task}"
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#set file names%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if (${scanner} == "ge") then
#different file paths for ge data
set subj_dir = ${subj}BRIKS
set bet_struct = ${study_dir}/${subj_dir}/struct/${subj}_in_optiBET_brain.nii.gz
set out_struct = ${study_dir}/${subj_dir}/struct/${subj}struct+orig.BRIK
else
set subj_dir = ${subj}_raw
set bet_struct = ${study_dir}/${subj_dir}/struct/${subj}struct_restore_optiBET_brain.nii.gz
set out_struct = ${study_dir}/${subj_dir}/struct/${subj}struct+orig.BRIK
endif
if (${scanner} == "prisma") then
#currently NOT using fieldmaps due to FM issue with unwarping on PRISMA data
set func_file = ${study_dir}/${subj_dir}/${task_dir}/${task}UCLA${subj}.nii.gz
else if (${scanner} == "ge") then
#different file paths for ge data
set func_file1 = ${study_dir}/${subj_dir}/archive/${subj}${task}_fm+orig.BRIK.gz
set func_file2 = ${study_dir}/${subj_dir}/archive/${subj}${task}_fm+orig.HEAD
set out_func = ${study_dir}/${subj_dir}/${task_dir}/${subj}${task}_fm+orig.BRIK
else
set func_file = (`ls ${study_dir}/${subj_dir}/${task_dir}/${subj}*.feat/filtered_func_data.nii.gz`)
set out_func = ${study_dir}/${subj_dir}/${task_dir}/${subj}${task}Func+orig.BRIK
endif

#set midpoint%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if (${scanner} == "ge") then
set npts = (`3dinfo -nv ${out_func}`)
echo "npts = ${npts}"
else
if (${task} == "FearAcq") then
set npts = (`ls ${study_dir}/${subj}_raw/raw/Fear_Cond_UCLA_1*/*.dcm |wc -l`)
set task_dir = Fear_cond/Fear_ext 
set npts = (`ls ${study_dir}/${subj}_raw/raw/Fear_Cond_UCLA_2*/*.dcm |wc -l`)
else if (${task} == "MID1") then
set npts = (`ls ${study_dir}/${subj}_raw/raw/MID_UCLA_4/*.dcm |wc -l`)
else if (${task} == "MID2") then
set npts = (`ls ${study_dir}/${subj}_raw/raw/MID_UCLA_5/*.dcm |wc -l`)
else
echo "error setting task files"
endif
endif
@ mp = (${npts} / 2)
echo "mp: ${mp}"

#run functions%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if (${run} == "ALL") then
echo "Converting to AFNI"
echo "subj = ${subj}"
#>>>>>>>>>>>>> convert structural file
3dcopy ${bet_struct} ${out_struct}

#>>>>>>>>>>>>> convert functional file
if (${scanner} == "ge") then
mkdir -p ${study_dir}/${subj_dir}/${task_dir}
cp ${func_file1} ${study_dir}/${subj_dir}/${task_dir}
cp ${func_file2} ${study_dir}/${subj_dir}/${task_dir}
gzip -d ${out_func}
else
3dcopy ${func_file} ${out_func}
endif

#>>>>>>>>>>>>> Outlier detection
3dToutcount -fraction -automask ${out_func} > ${study_dir}/${subj_dir}/${task_dir}/${subj}_OL_frac.txt
awk '$1 > .02' ${study_dir}/${subj_dir}/${task_dir}/${subj}_OL_frac.txt | wc -l > ${study_dir}/${subj_dir}/${task_dir}/${subj}_OL_overp02.txt
sed -n ${mp}p ${study_dir}/${subj_dir}/${task_dir}/${subj}_OL_frac.txt > ${study_dir}/${subj_dir}/${task_dir}/${subj}_OL_mid.txt

#>>>>>>>>>>>>> run conversion to taliarach coordinates (auto_tlrc)
cd ${study_dir}/${subj_dir}/struct/
@auto_tlrc  -no_ss -base TT_N27+tlrc -input ${subj}struct+orig.BRIK

#>>>>>>>>>>>>> run realignment
set tlrc_apar = ${study_dir}/${subj_dir}/struct/${subj}struct+tlrc.BRIK
cd ${study_dir}/${subj_dir}/${task_dir}
align_epi_anat.py -epi2anat -anat_has_skull no -anat ${out_struct} -epi ${out_func} -epi_base ${mp} -tlrc_apar ${tlrc_apar}
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
else if (${run} == "DSB") then
set tlrc_func = ${study_dir}/${subj_dir}/${task_dir}/${subj}${task}Func_tlrc_al+tlrc.BRIK
set despike = ${study_dir}/${subj_dir}/${task_dir}/${subj}${task}_DS+tlrc.BRIK
set blur_4 = ${study_dir}/${subj_dir}/${task_dir}/${subj}${task}_DSB4mm+tlrc.BRIK

	if (${scanner} == "trio") then
	#UCLA version
	3dDespike -prefix ${despike} ${tlrc_func}
	else if (${scanner} == "prisma") then
	#UCLA version
	3dDespike -prefix ${despike} ${tlrc_func}
	else if (${scanner} == "ge") then
	#UCSD VERSION
	3dDespike –ignore 2 –prefix ${despike} ${tlrc_func}
	endif 
#blurring/smoothing 4mm
3dBlurToFWHM -input ${despike} -prefix ${blur_4} -FWHM 4 –automask -quiet
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
else if (${run} == "mp") then
sed -n -e ${mp}p ${study_dir}/${subj_dir}/${task_dir}/${subj}_OL_frac.txt > ${study_dir}/${subj}_raw/${task_dir}/${subj}_OL_mid_frac.txt
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
else if (${run} == "SS") then
#>>>>>>>>>>>>> perform skull stripping
3dSkullStrip -input ${out_struct} -prefix ${study_dir}/${subj_dir}/struct/${subj}struct_SS+orig.BRIK
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
echo "done ${subj}"
endif
end
end
#3dDespike
#>> 3dDespike –ignore 2 –prefix <out11.0>  <out10.0>
#3dBlurToFWHM
#>> 3dBlurToFWHM –input <out11.0> -prefix <out12.0> -FWHM 4 –automask -quiet
#>> 3dBlurToFWHM –input <out11.0> -prefix <out12.0> -FWHM 6 –automask -quiet
