#!/bin/csh

# 1) converts to AFNI, 2) performs outlier detection, 3) optional skull stripping, 4) conversion to taliarach coords
# 5) realigns functional data to static template coords
# can be used on Fear Acq, Fear Ext, MID 1 or MID 2, with appropriate options at start
# comment out Structural conversion after first run!

#scanner = trio / prisma / ge
set scanner = trio
#task = FearAcq, FearExt, MID1, MID2
set task = FearAcq
#parts to run ALL (conversion, outlier detection, convert to taliarach & realign), SS = skull strip
set run = ALL

#-------------------------------------------------------------------------------------#
#set scan path
if (${scanner} == "trio") then
set study_dir = /space/raid6/data/craske/POS_NEG_EMO_RDOC/01_SUBJECTS_UCLA_TRIO
else if (${scanner} == "prisma") then
set study_dir = /space/raid6/data/craske/POS_NEG_EMO_RDOC/02_SUBJECTS_UCLA_PRISMA 	
else if (${scanner} == "ge") then
set study_dir = /space/raid6/data/craske/POS_NEG_EMO_RDOC/03_SUBJECTS_UCSD
else
echo "error setting scanner"
endif
echo "\nscanner: ${scanner}"


foreach subj (9204 9205 9206 9207 9208 9209 9211 9212 9213 9216 9217 9218 9219 9223 9224 9225 9226 9227 9228 9230 9231 9232 9233 9235 9236 9237 9238 9239 9241 9242 9243 9244 9245 9246 9247 9248 9251 9252 9254 9255 9257 9258 9259 9260 9261 9263 9264 9265 9266 9267 9268 9270 9271 9273 9274 9277 9279 9282 9283 9284 9285 9286 9287 9288 9289 9290) #(`cat AFNI_list`)

#9201 9202 9203 9204 9205 9206 9207 9208 9209 9211 
#9212 9213 9216 9217 9218 9219 9223 9224 9225 9226 
#9227 9228 9230 9231 9232 9233 9235 9236 9237 9238 
#9239 9241 9242 9243 9244 9245 9246 9247 9248 9251 
#9252 9254 9255 9257 9258 9259 9260 9261 9263 9264 
#9265 9266 9267 9268 9270 9271 9273 9274 9277 9279 
#9282 9283 9284 9285 9286 9287 9288 9289 9290

#set task files%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if (${task} == "FearAcq") then
set task_dir = Fear_cond/Fear_acq
set npts = (`ls ${study_dir}/${subj}_raw/raw/Fear_Cond_UCLA_1*/*.dcm |wc -l`)
else if (${task} == "FearExt") then
set task_dir = Fear_cond/Fear_ext 
set npts = (`ls ${study_dir}/${subj}_raw/raw/Fear_Cond_UCLA_2*/*.dcm |wc -l`)
else if (${task} == "MID1") then
set task_dir = MID/MID1
set npts = (`ls ${study_dir}/${subj}_raw/raw/MID_UCLA_4/*.dcm |wc -l`)
else if (${task} == "MID2") then
set task_dir = MID/MID2
set npts = (`ls ${study_dir}/${subj}_raw/raw/MID_UCLA_5/*.dcm |wc -l`)
else
echo "error setting task files"
endif
@ mp = (${npts} / 2)
echo "mp: ${mp}"
echo "\ntask: ${task}"
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#set file names%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
set bet_struct = ${study_dir}/${subj}_raw/struct/${subj}struct_restore_optiBET_brain.nii.gz
set out_struct = ${study_dir}/${subj}_raw/struct/${subj}struct+orig.BRIK
set func_file = (`ls ${study_dir}/${subj}_raw/${task_dir}/${subj}*.feat/filtered_func_data.nii.gz`)
set out_func = ${study_dir}/${subj}_raw/${task_dir}/${subj}${task}Func+orig.BRIK
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#run functions%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if (${run} == "ALL") then
echo "Converting to AFNI"
echo "subj = ${subj}"
#>>>>>>>>>>>>> convert structural file
3dcopy ${bet_struct} ${out_struct}

#>>>>>>>>>>>>> convert functional file
3dcopy ${func_file} ${out_func}

#>>>>>>>>>>>>> Outlier detection
3dToutcount -fraction -automask ${out_func} > ${study_dir}/${subj}_raw/${task_dir}/${subj}_OL_frac.txt
awk '$1 > .02' ${study_dir}/${subj}_raw/${task_dir}/${subj}_OL_frac.txt | wc -l > ${study_dir}/${subj}_raw/${task_dir}/${subj}_OL_overp02.txt
sed -n mp ${study_dir}/${subj}_raw/${task_dir}/${subj}_OL.txt > ${study_dir}/${subj}_raw/${task_dir}/${subj}_OL_mid.txt

#>>>>>>>>>>>>> run conversion to taliarach coordinates (auto_tlrc)
cd ${study_dir}/${subj}_raw/struct/
@auto_tlrc  -no_ss -base TT_N27+tlrc -input ${subj}struct+orig.BRIK

#>>>>>>>>>>>>> run realignment
cd study_dir
set anat = ${study_dir}/${subj}_raw/struct/${subj}struct+orig.BRIK
set epi = ${study_dir}/${subj}_raw/${task_dir}/${subj}${task}Func+orig.BRIK
set tlrc_apar = ${study_dir}/${subj}_raw/struct/${subj}struct+tlrc.BRIK
cd ${study_dir}/${subj}_raw/${task_dir}
align_epi_anat.py -epi2anat -anat_has_skull no -anat ${anat} -epi ${epi} -epi_base 97 -tlrc_apar ${tlrc_apar}
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
else if (${run} == "SS") then
#>>>>>>>>>>>>> perform skull stripping
3dSkullStrip -input ${out_struct} -prefix ${study_dir}/${subj}_raw/struct/${subj}struct_SS+orig.BRIK
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
echo "done ${subj}"
endif

#3dDespike
#>> 3dDespike –ignore 2 –prefix <out11.0>  <out10.0>
#3dBlurToFWHM
#>> 3dBlurToFWHM –input <out11.0> -prefix <out12.0> -FWHM 4 –automask -quiet
#>> 3dBlurToFWHM –input <out11.0> -prefix <out12.0> -FWHM 6 –automask -quiet
