#!/bin/csh

# 1) runs first level models

#scanner = trio / prisma / ge
set scanner = prisma
foreach task (FearExt)
#task = FearAcq, FearExt, MID1, MID2

#to run: main = CS+, CS-, CS+>CS-, last_four, amp_mod
set analysis = main

#-------------------------------------------------------------------------------------#
#set scan path
if (${scanner} == "trio") then
set study_dir = /space/raid6/data/craske/POS_NEG_EMO_RDOC/01_SUBJECTS_UCLA_TRIO
else if (${scanner} == "prisma") then
set study_dir = /space/raid6/data/craske/POS_NEG_EMO_RDOC/02_SUBJECTS_UCLA_PRISMA 	
else if (${scanner} == "ge") then
set study_dir = /space/raid6/data/craske/POS_NEG_EMO_RDOC/03_SUBJECTS_UCSD
else
echo "error setting scanner"
endif
echo "\nscanner: ${scanner}"

foreach subj (9292 9293 9294 9295 9296 9298 9300 9301 9302 9303 9304 9305 9306 9307 9308 9309 9310 9311 9312 9314 9315 9316 9317 9318 9319 9320 9321 9322 9323 9324 9325 9326 9327 9328)

#TRIO
#9201 9202 9203 9204 9205 9206 9207 9208 9209 9211 
#9212 9213 9216 9217 9218 9219 9223 9224 9225 9226 
#9227 9228 9230 9231 9232 9233 9235 9236 9237 9238 
#9239 9241 9242 9243 9244 9245 9246 9247 9248 9251 
#9252 9254 9255 9257 9258 9259 9260 9261 9263 9264 
#9265 9266 9267 9268 9270 9271 9273 9274 9277 9279 
#9282 9283 9284 9285 9286 9287 9288 9289 9290

#PRISMA
#9292 9293 9294 9295 9296 9298 9300 9301 9302 9303 
#9304 9305 9306 9307 9308 9309 9310 9311 9312 9314 
#9315 9316 9317 9318 9319 9320 9321 9322 9323 9324 
#9325 9326 9327 9328

#set task files%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if (${task} == "FearAcq") then
set task_dir = Fear_cond/Fear_acq
set taskname = Acq
else if (${task} == "FearExt") then
set task_dir = Fear_cond/Fear_ext 
set taskname = Ext
else if (${task} == "MID1") then
set task_dir = MID/Part1
else if (${task} == "MID2") then
set task_dir = MID/Part2
else
echo "error setting task files"
endif

if (${analysis} == "main") then
set analysis_dir = main_contrasts
else if (${analysis} == "last_four") then
set analysis_dir = last_four
else if (${analysis} == "amp_mod") then
set analysis_dir = amp_modulated
else
echo "error setting analysis dir"
endif

cd ${study_dir}/${subj}_raw/${task_dir}
mkdir ${analysis_dir}
3dDeconvolve \
-input ${study_dir}/${subj}_raw/${task_dir}/${subj}${task}_DecMe+tlrc.HEAD \
-censor ${study_dir}/${subj}_raw/${task_dir}/${subj}f_censor.1D \
-num_stimts 9 \
-stim_times 1 ${study_dir}/${subj}_raw/behav/${subj}${taskname}_CSPlus.txt 'BLOCK(6,1)' -stim_label 1 cs_plus \
-stim_times 2 ${study_dir}/${subj}_raw/behav/${subj}${taskname}_CSMinus.txt 'BLOCK(6,1)' -stim_label 2 cs_minus \
-stim_times 3 ${study_dir}/${subj}_raw/behav/${subj}${taskname}_Context.txt 'BLOCK(3,1)' -stim_label 3 context \
-stim_file 4 ${subj}${task}Func_vr_motion.1D'[0]' -stim_label 4 roll \
-stim_file 5 ${subj}${task}Func_vr_motion.1D'[1]' -stim_label 5 pitch \
-stim_file 6 ${subj}${task}Func_vr_motion.1D'[2]' -stim_label 6 yaw \
-stim_file 7 ${subj}${task}Func_vr_motion.1D'[3]' -stim_label 7 dx \
-stim_file 8 ${subj}${task}Func_vr_motion.1D'[4]' -stim_label 8 dy \
-stim_file 9 ${subj}${task}Func_vr_motion.1D'[5]' -stim_label 9 dz \
-num_glt 3 \
-gltsym 'SYM: +1*cs_plus -1*cs_minus ' -glt_label 1 "CSPlus-CSMinus" \
-gltsym 'SYM: +1*cs_plus' -glt_label 2 "CSPlus-Baseline" \
-gltsym 'SYM: +1*cs_minus' -glt_label 3 "CSMinus-Baseline" \
-fout -rout -tout -bout \
-nofull_first \
-x1D ${study_dir}/${subj}_raw/${task_dir}/${analysis_dir}/X.xmat.1D -xjpeg  ${study_dir}/${subj}_raw/${task_dir}/${analysis_dir}/X.jpg \
-bucket ${study_dir}/${subj}_raw/${task_dir}/${analysis_dir}/${subj}stats.buc #output file

cd ${study_dir}/${subj}_raw/${task_dir}/${analysis_dir}/
chmod 777 ${subj}stats.REML_cmd
./${subj}stats.REML_cmd
end
#################################


