#!/bin/csh

# 1) runs first level models

#scanner = trio / prisma / ge
set scanner = trio
foreach task (FearExt)
#task = FearAcq, FearExt, MID1, MID2

#to run: main = CS+, CS-, CS+>CS-, last_four, amp_mod
set analysis = last_four

#-------------------------------------------------------------------------------------#
#set scan path
if (${scanner} == "trio") then
set study_dir = /space/raid6/data/craske/POS_NEG_EMO_RDOC/01_SUBJECTS_UCLA_TRIO
else if (${scanner} == "prisma") then
set study_dir = /space/raid6/data/craske/POS_NEG_EMO_RDOC/02_SUBJECTS_UCLA_PRISMA 	
else if (${scanner} == "ge") then
set study_dir = /space/raid6/data/craske/POS_NEG_EMO_RDOC/03_SUBJECTS_UCSD
else
echo "error setting scanner"
endif
echo "\nscanner: ${scanner}"

foreach subj (9204 9205 9206 9207 9208 9209 9211 9212 9213 9216 9217 9218 9219 9223 9224 9225 9226 9227 9228 9230 9231 9232 9233 9235 9236 9237 9238 9239 9241 9242 9243 9244 9245 9246 9247 9248 9251 9252 9254 9255 9257 9258 9259 9260 9261 9263 9264 9265 9266 9267 9268 9270 9271 9273 9274 9277 9279 9282 9283 9284 9285 9286 9287 9288 9289 9290)

#9201 9202 9203 9204 9205 9206 9207 9208 9209 9211 
#9212 9213 9216 9217 9218 9219 9223 9224 9225 9226 
#9227 9228 9230 9231 9232 9233 9235 9236 9237 9238 
#9239 9241 9242 9243 9244 9245 9246 9247 9248 9251 
#9252 9254 9255 9257 9258 9259 9260 9261 9263 9264 
#9265 9266 9267 9268 9270 9271 9273 9274 9277 9279 
#9282 9283 9284 9285 9286 9287 9288 9289 9290

#set task files%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if (${task} == "FearAcq") then
set task_dir = Fear_cond/Fear_acq
set taskname = Acq
else if (${task} == "FearExt") then
set task_dir = Fear_cond/Fear_ext 
set taskname = Ext
else if (${task} == "MID1") then
set task_dir = MID/Part1
else if (${task} == "MID2") then
set task_dir = MID/Part2
else
echo "error setting task files"
endif

if (${analysis} == "main") then
set analysis_dir = main_contrasts
else if (${analysis} == "last_four") then
set analysis_dir = last_four
else if (${analysis} == "amp_mod") then
set analysis_dir = amp_modulated
else
echo "error setting analysis dir"
endif

cd ${study_dir}/${subj}_raw/${task_dir}
mkdir ${analysis_dir}
3dDeconvolve \
-input ${study_dir}/${subj}_raw/${task_dir}/${subj}${task}_DecMe+tlrc.HEAD \
-censor ${study_dir}/${subj}_raw/${task_dir}/${subj}f_censor.1D \
-num_stimts 11 \
-stim_times 1 ${study_dir}/${subj}_raw/behav/${subj}${taskname}_First_CSPlus.txt 'BLOCK(6,1)' -stim_label 1 first_cs_plus \
-stim_times 2 ${study_dir}/${subj}_raw/behav/${subj}${taskname}_Last_CSPlus.txt 'BLOCK(6,1)' -stim_label 2 last_cs_plus \
-stim_times 3 ${study_dir}/${subj}_raw/behav/${subj}${taskname}_First_CSMinus.txt 'BLOCK(6,1)' -stim_label 3 first_cs_minus \
-stim_times 4 ${study_dir}/${subj}_raw/behav/${subj}${taskname}_Last_CSMinus.txt 'BLOCK(6,1)' -stim_label 4 last_cs_minus \
-stim_times 5 ${study_dir}/${subj}_raw/behav/${subj}${taskname}_Context.txt 'BLOCK(3,1)' -stim_label 5 context \
-stim_file 6 ${subj}${task}Func_vr_motion.1D'[0]' -stim_label 6 roll \
-stim_file 7 ${subj}${task}Func_vr_motion.1D'[1]' -stim_label 7 pitch \
-stim_file 8 ${subj}${task}Func_vr_motion.1D'[2]' -stim_label 8 yaw \
-stim_file 9 ${subj}${task}Func_vr_motion.1D'[3]' -stim_label 9 dx \
-stim_file 10 ${subj}${task}Func_vr_motion.1D'[4]' -stim_label 10 dy \
-stim_file 11 ${subj}${task}Func_vr_motion.1D'[5]' -stim_label 11 dz \
-num_glt 4 \
-gltsym 'SYM: +1*first_cs_plus -1*first_cs_minus ' -glt_label 1 "Early_CSPlus-Early_CSMinus" \
-gltsym 'SYM: +1*last_cs_plus -1*last_cs_minus ' -glt_label 2 "Late_CSPlus-Late_CSMinus" \
-gltsym 'SYM: +1*first_cs_plus -1*last_cs_plus ' -glt_label 3 "Early_CSPlus-Late_CSPlus" \
-gltsym 'SYM: +1*first_cs_minus -1*last_cs_minus ' -glt_label 4 "Early_CSMinus-Late_CSMinus" \
-fout -rout -tout -bout \
-nofull_first \
-x1D ${study_dir}/${subj}_raw/${task_dir}/${analysis_dir}/X.xmat.1D -xjpeg  ${study_dir}/${subj}_raw/${task_dir}/${analysis_dir}/X.jpg \
-bucket ${study_dir}/${subj}_raw/${task_dir}/${analysis_dir}/${subj}stats.buc #output file

cd ${study_dir}/${subj}_raw/${task_dir}/${analysis_dir}/
chmod 777 ${subj}stats.REML_cmd
./${subj}stats.REML_cmd
end
#################################


