#!/bin/csh

#>>>>>>>>>>>>>>>
# Includes options for: 1) viewing bias field correction, 2) viewing BET/optiBET performance, 3) viewing output of inhomogeneity correction
# 4) viewing outliers, 5) viewing outliers above threshold, 6) viewing outliers at midpoint
# other visual inspection stages to be added...
#>>>>>>>>>>>>>>>

#scanner = trio / prisma / ge
set scanner = ge
#task = FearAcq, FearExt, MID1, MID2
set task = FearAcq
#QA stage = BET, BET_FMap, FEAT, OL_PLOT, OL_LIST, OL_MID, ALIGN, OVERLAP_CHECK
set QA = BET

#-------------------------------------------------------------------------------------#
#set scan path
if (${scanner} == "trio") then
set study_dir = /space/raid6/data/craske/POS_NEG_EMO_RDOC/01_SUBJECTS_UCLA_TRIO
else if (${scanner} == "prisma") then
set study_dir = /space/raid6/data/craske/POS_NEG_EMO_RDOC/02_SUBJECTS_UCLA_PRISMA 	
else if (${scanner} == "ge") then
set study_dir = /space/raid6/data/craske/POS_NEG_EMO_RDOC/03_SUBJECTS_UCSD
else
echo "error setting scanner"
endif
echo "\nscanner: ${scanner}"

foreach subj (05222201402)
#TRIO
#9201 9202 9203 9204 9205 9206 9207 9208 9209 9211 
#9212 9213 9216 9217 9218 9219 9223 9224 9225 9226 
#9227 9228 9230 9231 9232 9233 9235 9236 9237 9238 
#9239 9241 9242 9243 9244 9245 9246 9247 9248 9251 
#9252 9254 9255 9257 9258 9259 9260 9261 9263 9264 
#9265 9266 9267 9268 9270 9271 9273 9274 9277 9279 
#9282 9283 9284 9285 9286 9287 9288 9289 9290

#PRISMA
#9292 9293 9294 9295 9296 9298 9300 9301 9302 9303 
#9304 9305 9306 9307 9308 9309 9310 9311 9312 9314 
#9315 9316 9317 9318 9319 9320 9321 9322 9323 9324 
#9325 9326 9327 9328

#GE
#0106201503 0113201601 0114201601 0123201501 0128201501 0128201502 0129201601 0204201502 0210201501 0211201502 0215201601 0218201601 0305201501 0308201601 0308201602 0308201604 0310201501 0310201502 0404201403 0406201601 0406201602 0407201601 0407201602 0413201601 0416201502 0419201601 0424201401 0425201502 0427201401 0427201601 0430201401 0503201401 0506201402 0512201501 0516201601 0517201501 0519201401 0519201501 0520201401 0520201501 0520201502 0520201601 0522201402 0524201602 0620201601 0714201401 0727201601 0804201503 0807201502 0808201603 0811201401 0811201402 0811201403 0812201402 0818201401 0818201403 0828201403 0829201401 0902201401 0904201405 0905201401 0906201401 0910201401 0911201501 0916201501 0930201401 1016201502 1022201401 1028201401 1105201502 1106201403 1109201401 1114201401 1118201402 1119201503 1120201401 1210201401 1210201402 1210201501 1215201401 1218201402 1218201403 1218201501 1219201402


#echo "\nsubject: ${subj}"
#set task
if (${task} == "FearAcq") then
set task_dir = Fear_cond/Fear_acq
set const = ${study_dir}/scripts/08_behav/const_FAcq.txt
else if (${task} == "FearExt") then
set task_dir = Fear_cond/Fear_ext 
set const = ${study_dir}/scripts/08_behav/const_FExt.txt	
else if (${task} == "MID1") then
set task_dir = MID/MID1
else if (${task} == "MID2") then
set task_dir = MID/MID2
else
echo "error setting task files"
endif
#echo "\ntask: ${task}"

#set files
if (${scanner} == "ge") then
set base_img = ${study_dir}/${subj}BRIKS/struct/${subj}_in.nii.gz
set optibet_img = ${study_dir}/${subj}BRIKS/struct/${subj}_in_optiBET_brain.nii.gz
else
set base_img = ${study_dir}/${subj}_raw/struct/${subj}struct_restore.nii.gz
set optibet_img = ${study_dir}/${subj}_raw/struct/${subj}struct_restore_optiBET_brain.nii.gz
set feat_report = (`ls ${study_dir}/${subj}_raw/${task_dir}/${subj}*.feat/report_unwarp.html`)
set OL_file = ${study_dir}/${subj}_raw/${task_dir}/${subj}_OL_DS.txt
set n_OL = ${study_dir}/${subj}_raw/${task_dir}/${subj}_OL_overp02.txt
set mid = ${study_dir}/${subj}_raw/${task_dir}/${subj}_OL_mid_frac.txt
set struct_tlrc = ${study_dir}/${subj}_raw/struct/${subj}struct_SS+tlrc.BRIK
set OL_frac = ${study_dir}/${subj}_raw/${task_dir}/${subj}_OL_frac.txt
set struct_tlrc = ${study_dir}/${subj}_raw/struct/${subj}struct+tlrc.BRIK
set func_tlrc = ${study_dir}/${subj}_raw/${task_dir}/${subj}${task}Func_tlrc_al+tlrc.BRIK 
set fm_mag = ${study_dir}/${subj}_raw/FMaps/${subj}*FMMag.nii.gz
set fm_mag_brain = ${study_dir}/${subj}_raw/FMaps/${subj}*FMMag_brain.nii.gz
endif

#set files
if (${QA} == "BET") then
fslview ${base_img} ${optibet_img} -l Blue &
else if (${QA} == "BET_FMap") then
fslview ${fm_mag} ${fm_mag_brain} -l Blue &
else if (${QA} == "FEAT") then
firefox --new-tab ${feat_report} 	
else if (${QA} == "OL_PLOT") then
#1dplot ${OL_file} &
1dRplot -xax.lim 0 175 50 -yax.lim 0 1 .1 -one -col.color 1 2 -col.line.type 1 2 -i ${OL_frac} ${const} &
else if (${QA} == "OL_LIST") then
echo "subj = ${subj}"
cat ${n_OL}
else if (${QA} == "OL_MID") then
echo "subj = ${subj}"
cat ${mid}
else if (${QA} == "ALIGN") then
afni ${struct_tlrc} ${func_tlrc} &
else if (${QA} == "OVERLAP_CHECK") then
3dABoverlap ${study_dir}/${subj}_raw/struct/${subj}struct+orig.BRIK ${study_dir}/${subj}_raw/struct/${subj}struct_SS+orig.BRIK > ${study_dir}/${subj}_raw/struct/${subj}overlap.txt
else
echo "error setting files"
endif

#view optiBET
#fslview ${base_img} ${optibet_img} -l Blue &

###view FEAT report
#firefox --new-tab ${feat_report} 

###view OL
#1dplot ${OL_file} &

###view OL>300
#echo "subj = ${subj}"
#cat ${n_OL}

###view midpoint
#echo "subj = ${subj}"
#cat ${mid}

###view Struct Taliarch
#afni ${struct_tlrc} &


end


#---other
#(`ls ${dir}/${subj}_raw/Fear_cond/Fear_acq/${subj}Fear*.feat/filtered_func_data.nii.gz`)
#${study_dir}/${subj}_raw/Fear_cond/Fear_acq/${subj}FearAcq.feat/report_unwarp.html

#echo "base_img = ${base_img}"
#echo "bet_img = ${bet_img}"
###view bias field
#fslview ${pre_fast} ${base_img} &

###view BET & optiBET
#fslview ${base_img} ${bet_C_img} -l Red ${optibet_img} -l Blue &


#set pre_fast = ${study_dir}/${subj}_raw/struct/coMPRage${subj}.nii.gz
#set bet_img = ${study_dir}/${subj}_raw/struct/${subj}struct_restore_BET_brain.nii.gz
#set bet_C_img = ${study_dir}/${subj}_raw/struct/${subj}struct_restore_BET_C_brain.nii.gz
#${study_dir}/${subj}_raw/Fear_cond/Fear_ext/${subj}_OL_over300.txt
#${study_dir}/${subj}_raw/Fear_cond/Fear_acq/${subj}_OL_over300.txt

#${study_dir}/${subj}_raw/MID/Part2/${subj}_OL_mid.txt
#mid = ${study_dir}/${subj}_raw/Fear_cond/Fear_ext/${subj}_OL_mid.txt
#${study_dir}/${subj}_raw/Fear_cond/Fear_acq/${subj}_OL_mid.txt

