#!/bin/csh

# 1) runs first level models

#scanner = trio / prisma / ge
set scanner = trio
foreach task (FearAcq)
#task = FearAcq, FearExt, MID1, MID2

#to run: main = CS+, CS-, CS+>CS-, split_four, amp_mod
set analysis = split_four

#-------------------------------------------------------------------------------------#
#set scan path
if (${scanner} == "trio") then
set study_dir = /space/raid6/data/craske/POS_NEG_EMO_RDOC/01_SUBJECTS_UCLA_TRIO
else if (${scanner} == "prisma") then
set study_dir = /space/raid6/data/craske/POS_NEG_EMO_RDOC/02_SUBJECTS_UCLA_PRISMA 	
else if (${scanner} == "ge") then
set study_dir = /space/raid6/data/craske/POS_NEG_EMO_RDOC/03_SUBJECTS_UCSD
else
echo "error setting scanner"
endif
echo "\nscanner: ${scanner}"

foreach subj (9205 9206 9207 9208 9209 9211 9212 9213 9216 9217 9218 9219 9223 9224 9225 9226 9227 9228 9230 9231 9232 9233 9235 9236 9237 9238 9239 9241 9242 9243 9244 9245 9246 9247 9248 9251 9252 9254 9255 9257 9258 9259 9260 9261 9263 9264 9265 9266 9267 9268 9270 9271 9273 9274 9277 9279 9282 9283 9284 9285 9286 9287 9288 9289 9290)

#-------------------------------------------------------------------------------------#
3dcalc \
-fscale \
-a "FileName+orig[0]"\ 
-b "FileName+orig[6]"\ 
-expr "100 * b\a * step(1-abs(b/a))" \ 
-prefix FileNamePC

# baseline constant OR averaged constant if multiple runs exist
# sub-brck with regression coef
#step function controls outflow if baseline is close to 0
