#!/bin/csh
#
if ($#argv <2) then
        echo "Usage: censorstats [censor file] [stim file]  "
        exit 1
endif
 
set cen=$1
set stim=$2
@ cols = `awk '{print NF;exit}' ${stim}`
@ rows = `awk 'END{print NR}' ${cen}`
paste ${cen} ${stim} | head -n ${rows} > rm.$cen.$stim
# get averages
 
awk -v c=$cols '{if($1==1){for(i=2;i<=c+1;i++){a[i]+=$i;if($i>0){aa[i]++}}}else{for(i=2;i<=c+1;i++){b[i]+=$i;if($i>0){bb[i]++}}j++}}END{OFS="\t";for (k=2;k<=c+1;k++) {print k-1,aa[k]+0,bb[k]+0,sprintf("%.6f",(bb[k]+0)/aa[k]),sprintf("%.6f",a[k]/j),sprintf("%.6f",(b[k]+0)/j)}}' rm.$cen.$stim  > rm.$cen.$stim.1
set p1 = `cdf -p2t   -fico .05 $rows 1 1 | awk '{print $NF}'`
set p2 = `cdf -p2t   -fico .01 $rows 1 1 | awk '{print $NF}'`
1dCorrelate  -s   rm.$cen.$stim | grep -v "#" | awk -v c=$cols -v p=$p1 -v pp=$p2 'NR<c+1{OFS="\t";cs=substr($3,2);if(cs>p){s="*"};if(cs>pp){s="**"};print $3,s;s=""}'  >  rm.$cen.$stim.2
echo "Regr\tKeep_c\tCen_c\tCen_c/Keep_c\tKeep_m   \tCensor_m\tCorrel(s)\tSig"
paste  rm.$cen.$stim.?
rm rm.$cen.$stim*
